import { ArrowLeft, Landmark, Layers3 } from 'lucide-react';
import { useState } from 'react';
import { getActiveLichSuDiaLiLessons, getLichSuDiaLiLessonById, getLichSuDiaLiLessonQuestions, lichSuDiaLiSeed } from '../../../data/grade6/lich-su-dia-li';
import { LichSuDiaLiLessonCard } from '../components/LichSuDiaLiLessonCard';
import { LichSuDiaLiLessonDetailPage } from './LichSuDiaLiLessonDetailPage';
import { LichSuDiaLiPracticePage } from './LichSuDiaLiPracticePage';
type View = 'home' | 'detail' | 'practice';
type Props = { onBackToDashboard: () => void; };
export function LichSuDiaLiHomePage({ onBackToDashboard }: Props) { const lessons = getActiveLichSuDiaLiLessons(); const [view,setView] = useState<View>('home'); const [selectedLessonId,setSelectedLessonId] = useState(lessons[0]?.id ?? 1); const selectedLesson = getLichSuDiaLiLessonById(selectedLessonId) ?? lessons[0]; if (view === 'detail' && selectedLesson) return <LichSuDiaLiLessonDetailPage lesson={selectedLesson} onBack={() => setView('home')} onPractice={(id) => { setSelectedLessonId(id); setView('practice'); }} />; if (view === 'practice' && selectedLesson) return <LichSuDiaLiPracticePage lesson={selectedLesson} onBackToLesson={(id) => { setSelectedLessonId(id); setView('detail'); }} />; return <section className="mx-auto w-full max-w-6xl min-w-0 px-4 py-8 sm:px-6 lg:px-8"><button type="button" onClick={onBackToDashboard} className="mb-5 inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-bold text-slate-700 hover:bg-slate-50"><ArrowLeft className="h-4 w-4" />Dashboard</button><div className="w-full max-w-full min-w-0 rounded-3xl border border-amber-100 bg-gradient-to-r from-amber-50 via-white to-sky-50 p-5"><div className="flex min-w-0 flex-col gap-4 md:flex-row md:items-center md:justify-between"><div className="flex min-w-0 items-start gap-4"><div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-3xl bg-amber-600 text-white shadow-lg shadow-amber-200"><Landmark className="h-7 w-7" /></div><div className="min-w-0"><p className="text-sm font-black uppercase tracking-[0.16em] text-amber-700">Môn học đã mở</p><h1 className="mt-1 text-3xl font-black text-slate-950 [overflow-wrap:anywhere]">{lichSuDiaLiSeed.subjectTitle}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600 [overflow-wrap:anywhere]">Bộ bài học đã chuẩn hoá theo Lịch sử và Địa lí, có mốc thời gian, bản đồ/kĩ năng địa lí, ghi nhớ và kho câu hỏi luyện tập.</p></div></div><div className="max-w-full min-w-0 rounded-2xl bg-white/80 px-4 py-3 text-sm font-bold text-slate-700 ring-1 ring-amber-100 [overflow-wrap:anywhere]">{lessons.length} bài - {lichSuDiaLiSeed.questions.length} câu hỏi</div></div></div><div className="mt-6"><div className="mb-4 flex min-w-0 items-center gap-2"><Layers3 className="h-5 w-5 shrink-0 text-amber-700" /><h2 className="text-xl font-black text-slate-950 [overflow-wrap:anywhere]">Lộ trình: {lichSuDiaLiSeed.subjectTitle}</h2></div><div className="grid min-w-0 gap-4 md:grid-cols-[repeat(2,minmax(0,1fr))]">{lessons.map((lesson) => <LichSuDiaLiLessonCard key={lesson.id} lesson={lesson} questionCount={getLichSuDiaLiLessonQuestions(lesson.id).length} onSelect={(id) => { setSelectedLessonId(id); setView('detail'); }} />)}</div></div></section>; }
